---

- name: Check squid3 configuration and restart
  command: /usr/sbin/squid3 -k parse
  notify: [ 'Restart squid3' ]

- name: Restart squid3
  service:
    name: 'squid3'
    state: 'restarted'

- name: Check squid3 configuration and reload
  command: /usr/sbin/squid3 -k parse
  notify: [ 'Reload squid3' ]

- name: Reload squid3
  service:
    name: 'squid3'
    state: 'reloaded'
